version: "3"

networks:
  webnet:
services:
  web:
    image: saiganesh/rpinode
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure      
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - webnet
  mongo:
    image: dhermanns/rpi-mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongodata:/data/db
    ports:
      - "27017"
    networks:
      - webnet
volumes:
  mongodata:
    
    
