version: "3"
networks:
  webnet:
services:
  web:
    image: saiganesh/rpisample
    depends_on:
      - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure      
    ports:
      - "80:3000"
    networks:
      - webnet
  mongo:
    image: cretzel/rpi-mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - webnet
volumes:
  mongodb:
    
    
